export const USERS_ALL_REQUEST = "USERS_ALL_REQUEST"
export const USERS_ALL_SUCCESS = "USERS_ALL_SUCCESS"
export const USERS_ALL_FAIL = "USERS_ALL_FAIL"

export const USERS_FEMALE_REQUEST = "USERS_FEMALE_REQUEST"
export const USERS_FEMALE_SUCCESS = "USERS_FEMALE_SUCCESS"
export const USERS_FEMALE_FAIL = "USERS_FEMALE_FAIL"

export const USERS_MALE_REQUEST = "USERS_MALE_REQUEST"
export const USERS_MALE_SUCCESS = "USERS_MALE_SUCCESS"
export const USERS_MALE_FAIL = "USERS_MALE_FAIL"